name: example
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_viper:
    path: ../
  equatable: ^0.4.0
  http: ^0.12.2
  cloud_firestore: ^0.14.3
  firebase_auth: 0.18.4+1
  firebase_core: ^0.5.3
  image_picker: ^0.6.7+14
  firebase_storage: ^5.1.0
  flutter_svg: 0.19.0
  pin_code_fields: 5.0.0
  dartz: ^0.8.6
  connectivity: ^0.4.9+5
  data_connection_checker: ^0.3.4
  get_it: ^2.0.1
  bot_toast: ^3.0.5



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/user_info.png
    - assets/images/null_photo.png
    - assets/images/car_images/frame.png
    - assets/images/car_images/car1.png
    - assets/images/car_images/car2.png
    - assets/images/car_images/car3.png
    - assets/images/car_images/car4.png
    - assets/images/docs_images/doc1.png
    - assets/images/docs_images/doc2.png
    - assets/images/docs_images/doc3.png
    - assets/images/docs_images/doc4.png
    - assets/icons/arrow_back.png
    - assets/icons/plus.png
    - assets/icons/left_burger.png
    - assets/icons/center_burger.png
    - assets/icons/setting.png
    - assets/icons/edit.png
    - assets/icons/star.png
    - assets/icons/rating.png
    - assets/icons/like.png
    - assets/icons/dislike.png
    - assets/icons/icn_photo.png
    - assets/icons/icn_doc.png
    - assets/icons/car_evacuator.png
    - assets/icons/car_fuel.png
    - assets/icons/car_keys.png
    - assets/icons/car_repair.png
    - assets/icons/car_towing.png
    - assets/icons/car_wheel.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/InterBold.ttf
        - asset: assets/InterRegular.ttf



  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
