name: bloc_viper
description: BLoC VIPER package.
version: 4.2.0
author: MaximKuznetsov1999<makss-1099@mail.ru>
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
